const fs = require('fs');
const path = require('path');
require('dotenv').config();

const dirPath = path.join(__dirname, '../src/environments');

// Helper to write environment files
const writeEnvironmentFile = (isProduction, useEmulators) => {
  const envConfigFile = `// This file is auto-generated by target scripts/set-env.js
export const environment = {
  production: ${isProduction},
  useEmulators: ${useEmulators},
  firebase: {
    apiKey: '${process.env.FIREBASE_API_KEY}',
    authDomain: '${process.env.FIREBASE_AUTH_DOMAIN}',
    projectId: '${process.env.FIREBASE_PROJECT_ID}',
    storageBucket: '${process.env.FIREBASE_STORAGE_BUCKET}',
    messagingSenderId: '${process.env.FIREBASE_MESSAGING_SENDER_ID}',
    appId: '${process.env.FIREBASE_APP_ID}'
  },
  supabase: {
    url: '${process.env.SUPABASE_URL || ''}',
    anonKey: '${process.env.SUPABASE_ANON_KEY || ''}',
    screenshotBucket: '${process.env.SCREENSHOT_BUCKET || process.env.SUPABASE_SCREENSHOT_BUCKET || 'screenshots'}'
  }
};
`;

  const fileName = isProduction ? 'environment.production.ts' : 'environment.ts';
  const targetPath = path.join(dirPath, fileName);
  fs.writeFileSync(targetPath, envConfigFile);
  console.log(`Generated ${targetPath} successfully.`);
};

// Create the directory if it doesn't exist
if (!fs.existsSync(dirPath)){
    fs.mkdirSync(dirPath, { recursive: true });
}

// Generate the Dev build targeting Emulators
writeEnvironmentFile(false, true);

// Generate the Prod build not using emulators
writeEnvironmentFile(true, false);

